image: debian/buster
sources:
  - https://git.sr.ht/~matthiasbeyer/option-inspect
tasks:
  - install: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - build: |
      cd option-inspect
      PATH="$HOME/.cargo/bin:$PATH" cargo build --all --all-features
  - test: |
      cd option-inspect
      PATH="$HOME/.cargo/bin:$PATH" cargo test --all --all-features
triggers:
  - action: email
    condition: always
    to: mail@beyermatthias.de

